spring:
  application:
    name: TaskManager

  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


#Включение и отключение кеша
cache:
  redis:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  api-docs:
    path: /api-docs
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      access: unrestricted

  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    name: /var/log/taskmanager/application.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"