spring:
  application:
    name: TaskManager

  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


#Включение и отключение кеша
cache:
  redis:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  api-docs:
    path: /api-docs
    enabled: true